INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Cool Minimal Couch','5000','Modern Minimal Design Couch','FURNITURE','Cool Minimal Couch.jpg',15);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Cool Modern Lights','1200','Decorate your Home With these Cool Lights','DECOR','Cool Modern Lights.jpg',30);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Cool Modern Stylish Lights','1400','Modern Aesthetic Lights','DECOR','Cool Modern Stylish Lights.jpg',26);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Cool Wall Decor','5000','Moden Minimal Decor','DECOR','Cool Wall Decor.jpg',16);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Couch','9000','A very Comfy Couch','FURNITURE','Couch 01.jpg',17);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Curtains','980','These Curatins are made Hand Crafted with Premium Quality','FURNISHINGS','Curtains_1 04.jpg',34);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Cushion Chair','3400','Wooden Handicrafted Chair with good build quality','FURNITURE','Cushion Chair 01.jpg',25);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'HeavyDesign Curtainst','600','These Curtains are handcrafted by an Expert Handloom','FURNISHINGS','HeavyDesign Curtainst 04.jpg',16);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Instant Coffee Maker','5400','A premium instant coffee maker','APPLIANCES','Instant Coffee Maker 05.jpg',15);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Kitchen Decor Lights','1300','Decorating Lights for Kitchen','DECOR','Kitchen Decor Lights 03.jpg',20);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Luxury Wooden Chair','1500','This chair is made of an Expensive Wood','FURNITURE','Luxury Wooden Chair 01.jpg',29);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Massager','1500','This is a very premium massager for stress relief','APPLIANCES','Massager 05.jpg',41);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Modern Aesthetic Blanket','1000','An aesthetic blanket made with micro fiber','FURNISHINGS','Modern Aesthetic Blanket.jpg',36);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Modern Bed Sheet with Pillow Covers','1500','Best bedsheets with pillow covers','FURNISHINGS','Modern Bed Sheet with Pillow Covers.jpg',29);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Modern Cupboard Wardrobe','3000','This wardrobe is made with strong wood','STORAGE','Modern Cupboard Wardrobe.jpg',14);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Modern Flower Pots','700','These flower pots make as good Decor','DECOR','Modern Flower Pots.jpg',34);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Modern Hair Dryer','4000','This is modern premium quality Hair Dryer','APPLIANCES','Modern Hair Dryer 05.jpg',26);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Modern WallMount Cupboard','15000','This is a wall mount cupboard for books','STORAGE','Modern WallMount Cupboard.jpg',15);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Modern Wardrobe','12000','This modern wardrobe is very minimal and simple','STORAGE','Modern Wardrobe.jpg',19);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Modern White Cabinet','10000','This is a white cabinet with minimal design','STORAGE','Modern White Cabinet.jpg',14);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Modern Wooden Cupboard','12000','This cupboard is made of sandal wood','STORAGE','Modern Wooden Cupboard.jpg',18);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Plain White Luxury Bed Sheet','1500','These bed sheets are made of best quality fiber','FURNISHINGS','Plain White Luxury Bed Sheet.jpg',24);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Washing Machine','15000','This is an automatic washing machine','APPLIANCES','Washing Machine 05.jpg',26);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'2 Seat Dining Tanle','20000','This is a premium aesthetic dining table','FURNITURE','2 Seat Dining Tanle 01.jpg',34);
INSERT INTO PRODUCTS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,'Cleaning Bot','5000','This bot cleans your room automatically','APPLIANCES','Cleaning Bot 05.jpg',25);
